services:
  postgres:
    image: "postgres:15"
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: interway-app-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres15_data

volumes:
  postgres_data: